// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { BatchUploadResumesResumesBatchUploadPostData, BatchUploadResumesResumesBatchUploadPostErrors, BatchUploadResumesResumesBatchUploadPostResponses, DebugPathsDebugPathsGetData, DebugPathsDebugPathsGetResponses, GetCandidateCandidatesCandidateIdGetData, GetCandidateCandidatesCandidateIdGetErrors, GetCandidateCandidatesCandidateIdGetResponses, HealthHealthGetData, HealthHealthGetResponses, ListCandidatesCandidatesGetData, ListCandidatesCandidatesGetResponses, ListResumesResumesGetData, ListResumesResumesGetResponses, RootGetData, RootGetResponses, TempUploadResumeResumesTempUploadPostData, TempUploadResumeResumesTempUploadPostErrors, TempUploadResumeResumesTempUploadPostResponses, UpdateCandidateCandidatesUpdatePostData, UpdateCandidateCandidatesUpdatePostErrors, UpdateCandidateCandidatesUpdatePostResponses, UploadResumeResumesUploadPostData, UploadResumeResumesUploadPostErrors, UploadResumeResumesUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Debug Paths
 */
export const debugPathsDebugPathsGet = <ThrowOnError extends boolean = false>(options?: Options<DebugPathsDebugPathsGetData, ThrowOnError>) => (options?.client ?? client).get<DebugPathsDebugPathsGetResponses, unknown, ThrowOnError>({ url: '/debug/paths', ...options });

/**
 * List Candidates
 */
export const listCandidatesCandidatesGet = <ThrowOnError extends boolean = false>(options?: Options<ListCandidatesCandidatesGetData, ThrowOnError>) => (options?.client ?? client).get<ListCandidatesCandidatesGetResponses, unknown, ThrowOnError>({ url: '/candidates', ...options });

/**
 * Get Candidate
 */
export const getCandidateCandidatesCandidateIdGet = <ThrowOnError extends boolean = false>(options: Options<GetCandidateCandidatesCandidateIdGetData, ThrowOnError>) => (options.client ?? client).get<GetCandidateCandidatesCandidateIdGetResponses, GetCandidateCandidatesCandidateIdGetErrors, ThrowOnError>({ url: '/candidates/{candidate_id}', ...options });

/**
 * List Resumes
 */
export const listResumesResumesGet = <ThrowOnError extends boolean = false>(options?: Options<ListResumesResumesGetData, ThrowOnError>) => (options?.client ?? client).get<ListResumesResumesGetResponses, unknown, ThrowOnError>({ url: '/resumes', ...options });

/**
 * Temp Upload Resume
 */
export const tempUploadResumeResumesTempUploadPost = <ThrowOnError extends boolean = false>(options: Options<TempUploadResumeResumesTempUploadPostData, ThrowOnError>) => (options.client ?? client).post<TempUploadResumeResumesTempUploadPostResponses, TempUploadResumeResumesTempUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/resumes/temp-upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Upload Resume
 */
export const uploadResumeResumesUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadResumeResumesUploadPostData, ThrowOnError>) => (options.client ?? client).post<UploadResumeResumesUploadPostResponses, UploadResumeResumesUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/resumes/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Batch Upload Resumes
 */
export const batchUploadResumesResumesBatchUploadPost = <ThrowOnError extends boolean = false>(options: Options<BatchUploadResumesResumesBatchUploadPostData, ThrowOnError>) => (options.client ?? client).post<BatchUploadResumesResumesBatchUploadPostResponses, BatchUploadResumesResumesBatchUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/resumes/batch_upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Update Candidate
 */
export const updateCandidateCandidatesUpdatePost = <ThrowOnError extends boolean = false>(options: Options<UpdateCandidateCandidatesUpdatePostData, ThrowOnError>) => (options.client ?? client).post<UpdateCandidateCandidatesUpdatePostResponses, UpdateCandidateCandidatesUpdatePostErrors, ThrowOnError>({
    url: '/candidates/update',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
