// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BatchUploadResponse
 */
export type BatchUploadResponse = {
    /**
     * Results
     */
    results: Array<UploadResponse>;
};

/**
 * Body_batch_upload_resumes_resumes_batch_upload_post
 */
export type BodyBatchUploadResumesResumesBatchUploadPost = {
    /**
     * Files
     */
    files: Array<Blob | File>;
    /**
     * Resume Source Link
     */
    resume_source_link?: string | null;
};

/**
 * Body_temp_upload_resume_resumes_temp_upload_post
 */
export type BodyTempUploadResumeResumesTempUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_resume_resumes_upload_post
 */
export type BodyUploadResumeResumesUploadPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Linkedin Url
     */
    linkedin_url?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * School
     */
    school?: string | null;
    /**
     * Degree
     */
    degree?: string | null;
    /**
     * Terminal Degree Year
     */
    terminal_degree_year?: string | null;
    /**
     * Current Job Title
     */
    current_job_title?: string | null;
    /**
     * Latest Company
     */
    latest_company?: string | null;
    /**
     * Skills
     */
    skills?: string | null;
    /**
     * Certifications
     */
    certifications?: string | null;
    /**
     * Professional Summary
     */
    professional_summary?: string | null;
    /**
     * Portfolio Url
     */
    portfolio_url?: string | null;
    /**
     * Github Url
     */
    github_url?: string | null;
    /**
     * Academic Title
     */
    academic_title?: string | null;
    /**
     * Research Area
     */
    research_area?: string | null;
    /**
     * Publications Summary
     */
    publications_summary?: string | null;
    /**
     * Awards Summary
     */
    awards_summary?: string | null;
    /**
     * Resume Source Link
     */
    resume_source_link?: string | null;
};

/**
 * CandidateOut
 */
export type CandidateOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Linkedin Url
     */
    linkedin_url?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * School
     */
    school?: string | null;
    /**
     * Degree
     */
    degree?: string | null;
    /**
     * Terminal Degree Year
     */
    terminal_degree_year?: string | null;
    /**
     * Current Job Title
     */
    current_job_title?: string | null;
    /**
     * Skills
     */
    skills?: string | null;
    /**
     * Professional Summary
     */
    professional_summary?: string | null;
    /**
     * Latest Company
     */
    latest_company?: string | null;
    /**
     * Certifications
     */
    certifications?: string | null;
    /**
     * Portfolio Url
     */
    portfolio_url?: string | null;
    /**
     * Github Url
     */
    github_url?: string | null;
    /**
     * Academic Title
     */
    academic_title?: string | null;
    /**
     * Research Area
     */
    research_area?: string | null;
    /**
     * Publications Summary
     */
    publications_summary?: string | null;
    /**
     * Awards Summary
     */
    awards_summary?: string | null;
    /**
     * State Full
     */
    state_full?: string | null;
    /**
     * Location Display
     */
    location_display?: string | null;
    /**
     * Years Experience Overall
     */
    years_experience_overall?: string | null;
    /**
     * Years Experience In Field
     */
    years_experience_in_field?: string | null;
    /**
     * Title Seniority Signal
     */
    title_seniority_signal?: string | null;
    /**
     * Education Stage Signal
     */
    education_stage_signal?: string | null;
    /**
     * Career Level Overall
     */
    career_level_overall?: string | null;
    /**
     * Career Level Target Field
     */
    career_level_target_field?: string | null;
    /**
     * Career Level Confidence
     */
    career_level_confidence?: string | null;
    /**
     * Career Level Reason
     */
    career_level_reason?: string | null;
    /**
     * Resume Source Link
     */
    resume_source_link?: string | null;
    /**
     * Resume File Name
     */
    resume_file_name?: string | null;
    /**
     * Resume File Type
     */
    resume_file_type?: string | null;
    /**
     * Resume Page Count
     */
    resume_page_count: number;
    /**
     * Resume Text Quality
     */
    resume_text_quality?: string | null;
    /**
     * Needs Review
     */
    needs_review: string;
    /**
     * Review Reason
     */
    review_reason?: string | null;
    /**
     * Parsed Char Count
     */
    parsed_char_count: number;
    /**
     * Llm Input Char Count
     */
    llm_input_char_count: number;
    /**
     * Fields Found Count
     */
    fields_found_count: number;
    /**
     * Required Fields Found Count
     */
    required_fields_found_count: number;
    /**
     * Required Fields Missing
     */
    required_fields_missing?: string | null;
    /**
     * Extraction Confidence
     */
    extraction_confidence?: string | null;
    /**
     * Flag Reasons
     */
    flag_reasons?: string | null;
    /**
     * Flag Details
     */
    flag_details?: string | null;
    /**
     * Extracted Fields
     */
    extracted_fields?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CandidateOutPartial
 */
export type CandidateOutPartial = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Linkedin Url
     */
    linkedin_url?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * School
     */
    school?: string | null;
    /**
     * Degree
     */
    degree?: string | null;
    /**
     * Terminal Degree Year
     */
    terminal_degree_year?: string | null;
    /**
     * Current Job Title
     */
    current_job_title?: string | null;
    /**
     * Skills
     */
    skills?: string | null;
    /**
     * Professional Summary
     */
    professional_summary?: string | null;
    /**
     * Latest Company
     */
    latest_company?: string | null;
    /**
     * Certifications
     */
    certifications?: string | null;
    /**
     * Portfolio Url
     */
    portfolio_url?: string | null;
    /**
     * Github Url
     */
    github_url?: string | null;
    /**
     * Academic Title
     */
    academic_title?: string | null;
    /**
     * Research Area
     */
    research_area?: string | null;
    /**
     * Publications Summary
     */
    publications_summary?: string | null;
    /**
     * Awards Summary
     */
    awards_summary?: string | null;
    /**
     * State Full
     */
    state_full?: string | null;
    /**
     * Location Display
     */
    location_display?: string | null;
    /**
     * Years Experience Overall
     */
    years_experience_overall?: string | null;
    /**
     * Years Experience In Field
     */
    years_experience_in_field?: string | null;
    /**
     * Title Seniority Signal
     */
    title_seniority_signal?: string | null;
    /**
     * Education Stage Signal
     */
    education_stage_signal?: string | null;
    /**
     * Career Level Overall
     */
    career_level_overall?: string | null;
    /**
     * Career Level Target Field
     */
    career_level_target_field?: string | null;
    /**
     * Career Level Confidence
     */
    career_level_confidence?: string | null;
    /**
     * Career Level Reason
     */
    career_level_reason?: string | null;
    /**
     * Resume Source Link
     */
    resume_source_link?: string | null;
    /**
     * Resume File Name
     */
    resume_file_name?: string | null;
    /**
     * Resume File Type
     */
    resume_file_type?: string | null;
    /**
     * Resume Page Count
     */
    resume_page_count?: number | null;
    /**
     * Resume Text Quality
     */
    resume_text_quality?: string | null;
    /**
     * Needs Review
     */
    needs_review?: string | null;
    /**
     * Review Reason
     */
    review_reason?: string | null;
    /**
     * Parsed Char Count
     */
    parsed_char_count?: number | null;
    /**
     * Llm Input Char Count
     */
    llm_input_char_count?: number | null;
    /**
     * Fields Found Count
     */
    fields_found_count?: number | null;
    /**
     * Required Fields Found Count
     */
    required_fields_found_count?: number | null;
    /**
     * Required Fields Missing
     */
    required_fields_missing?: string | null;
    /**
     * Extraction Confidence
     */
    extraction_confidence?: string | null;
    /**
     * Flag Reasons
     */
    flag_reasons?: string | null;
    /**
     * Flag Details
     */
    flag_details?: string | null;
    /**
     * Extracted Fields
     */
    extracted_fields?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ResumeOut
 */
export type ResumeOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Candidate Id
     */
    candidate_id?: number | null;
    /**
     * Resume File Name
     */
    resume_file_name: string;
    /**
     * Resume File Type
     */
    resume_file_type?: string | null;
    /**
     * Saved Path
     */
    saved_path: string;
    /**
     * Content Sha256
     */
    content_sha256?: string | null;
    /**
     * Normalized Text Sha256
     */
    normalized_text_sha256?: string | null;
    /**
     * Parsed Char Count
     */
    parsed_char_count: number;
    /**
     * Resume Page Count
     */
    resume_page_count: number;
    /**
     * Resume Text Quality
     */
    resume_text_quality?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UploadResponse
 */
export type UploadResponse = {
    candidate: CandidateOut;
    resume: ResumeOut;
    /**
     * Duplicate
     */
    duplicate?: boolean;
    /**
     * Duplicate Type
     */
    duplicate_type?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type DebugPathsDebugPathsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/debug/paths';
};

export type DebugPathsDebugPathsGetResponses = {
    /**
     * Response Debug Paths Debug Paths Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DebugPathsDebugPathsGetResponse = DebugPathsDebugPathsGetResponses[keyof DebugPathsDebugPathsGetResponses];

export type ListCandidatesCandidatesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/candidates';
};

export type ListCandidatesCandidatesGetResponses = {
    /**
     * Response List Candidates Candidates Get
     *
     * Successful Response
     */
    200: Array<CandidateOut>;
};

export type ListCandidatesCandidatesGetResponse = ListCandidatesCandidatesGetResponses[keyof ListCandidatesCandidatesGetResponses];

export type GetCandidateCandidatesCandidateIdGetData = {
    body?: never;
    path: {
        /**
         * Candidate Id
         */
        candidate_id: number;
    };
    query?: never;
    url: '/candidates/{candidate_id}';
};

export type GetCandidateCandidatesCandidateIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCandidateCandidatesCandidateIdGetError = GetCandidateCandidatesCandidateIdGetErrors[keyof GetCandidateCandidatesCandidateIdGetErrors];

export type GetCandidateCandidatesCandidateIdGetResponses = {
    /**
     * Successful Response
     */
    200: CandidateOut;
};

export type GetCandidateCandidatesCandidateIdGetResponse = GetCandidateCandidatesCandidateIdGetResponses[keyof GetCandidateCandidatesCandidateIdGetResponses];

export type ListResumesResumesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/resumes';
};

export type ListResumesResumesGetResponses = {
    /**
     * Response List Resumes Resumes Get
     *
     * Successful Response
     */
    200: Array<ResumeOut>;
};

export type ListResumesResumesGetResponse = ListResumesResumesGetResponses[keyof ListResumesResumesGetResponses];

export type TempUploadResumeResumesTempUploadPostData = {
    body: BodyTempUploadResumeResumesTempUploadPost;
    path?: never;
    query?: never;
    url: '/resumes/temp-upload';
};

export type TempUploadResumeResumesTempUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TempUploadResumeResumesTempUploadPostError = TempUploadResumeResumesTempUploadPostErrors[keyof TempUploadResumeResumesTempUploadPostErrors];

export type TempUploadResumeResumesTempUploadPostResponses = {
    /**
     * Successful Response
     */
    200: UploadResponse;
};

export type TempUploadResumeResumesTempUploadPostResponse = TempUploadResumeResumesTempUploadPostResponses[keyof TempUploadResumeResumesTempUploadPostResponses];

export type UploadResumeResumesUploadPostData = {
    body: BodyUploadResumeResumesUploadPost;
    path?: never;
    query?: never;
    url: '/resumes/upload';
};

export type UploadResumeResumesUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadResumeResumesUploadPostError = UploadResumeResumesUploadPostErrors[keyof UploadResumeResumesUploadPostErrors];

export type UploadResumeResumesUploadPostResponses = {
    /**
     * Successful Response
     */
    200: UploadResponse;
};

export type UploadResumeResumesUploadPostResponse = UploadResumeResumesUploadPostResponses[keyof UploadResumeResumesUploadPostResponses];

export type BatchUploadResumesResumesBatchUploadPostData = {
    body: BodyBatchUploadResumesResumesBatchUploadPost;
    path?: never;
    query?: never;
    url: '/resumes/batch_upload';
};

export type BatchUploadResumesResumesBatchUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchUploadResumesResumesBatchUploadPostError = BatchUploadResumesResumesBatchUploadPostErrors[keyof BatchUploadResumesResumesBatchUploadPostErrors];

export type BatchUploadResumesResumesBatchUploadPostResponses = {
    /**
     * Successful Response
     */
    200: BatchUploadResponse;
};

export type BatchUploadResumesResumesBatchUploadPostResponse = BatchUploadResumesResumesBatchUploadPostResponses[keyof BatchUploadResumesResumesBatchUploadPostResponses];

export type UpdateCandidateCandidatesUpdatePostData = {
    body: CandidateOutPartial;
    path?: never;
    query: {
        /**
         * Id
         */
        id: number;
    };
    url: '/candidates/update';
};

export type UpdateCandidateCandidatesUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCandidateCandidatesUpdatePostError = UpdateCandidateCandidatesUpdatePostErrors[keyof UpdateCandidateCandidatesUpdatePostErrors];

export type UpdateCandidateCandidatesUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: CandidateOut;
};

export type UpdateCandidateCandidatesUpdatePostResponse = UpdateCandidateCandidatesUpdatePostResponses[keyof UpdateCandidateCandidatesUpdatePostResponses];
